//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDemo.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdmin
    {
        public int Admin_id { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string f_name { get; set; }
        public string l_name { get; set; }
    }
}
